package com.aditya.personalbudget.service;

import com.aditya.personalbudget.repository.ChitRepository;
import com.aditya.personalbudget.repository.CategoryRepository;
import com.aditya.personalbudget.domain.type.CategoryKind;
import com.aditya.personalbudget.domain.type.AccountType;
import com.aditya.personalbudget.domain.entity.Chit;
import com.aditya.personalbudget.domain.entity.Category;
import com.aditya.personalbudget.domain.entity.Account;
import com.aditya.personalbudget.domain.entity.JournalEntry;
import com.aditya.personalbudget.domain.entity.JournalLine;
import com.aditya.personalbudget.domain.type.VoucherType;
import com.aditya.personalbudget.dto.JournalDtos.EntryView;
import com.aditya.personalbudget.dto.JournalDtos.LineView;
import com.aditya.personalbudget.exception.BusinessException;
import com.aditya.personalbudget.exception.NotFoundException;
import com.aditya.personalbudget.domain.entity.ClaimRepayment;
import com.aditya.personalbudget.repository.AccountRepository;
import com.aditya.personalbudget.repository.ClaimRepaymentRepository;
import com.aditya.personalbudget.repository.HostedChitRepository;
import com.aditya.personalbudget.repository.JournalEntryRepository;
import com.aditya.personalbudget.repository.JournalLineRepository;
import com.aditya.personalbudget.security.UserContext;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * The general ledger: the only place where journal entries are written.
 * <p>
 * Accounting rules enforced on every posting:
 * <ol>
 *   <li>At least two lines, touching at least two different accounts (or categories / chits)</li>
 *   <li>Each line is either a debit or a credit, never both, never zero</li>
 *   <li>Total debits equal total credits</li>
 *   <li>All accounts, categories and chits belong to the caller's tenant</li>
 *   <li>Lines on the Expenses / Income account carry a category of that kind (Miscellaneous / Other
 *       income when none is given); lines on Chit Funds carry their chit; other lines carry neither</li>
 * </ol>
 */
@Service
public class LedgerService {

    /** Source types for entries generated by other features (they are edited through that feature). */
    public static final String SOURCE_ACCOUNT_OPENING = "ACCOUNT_OPENING";
    public static final String SOURCE_CHIT_INSTALLMENT = "CHIT_INSTALLMENT";
    public static final String SOURCE_CHIT_PAYOUT = "CHIT_PAYOUT";
    public static final String SOURCE_RECURRING = "RECURRING";
    public static final String SOURCE_QUICK = "QUICK";
    public static final String SOURCE_EXPENSE = "EXPENSE";
    public static final String SOURCE_CLAIM = "CLAIM";
    public static final String SOURCE_CLAIM_REPAYMENT = "CLAIM_REPAYMENT";
    public static final String SOURCE_CLAIM_INTEREST = "CLAIM_INTEREST";
    public static final String SOURCE_REFUND = "EXPENSE_REFUND";
    public static final String SOURCE_REVERSAL = "REVERSAL";

    private final AccountRepository accounts;
    private final JournalEntryRepository entries;
    private final JournalLineRepository lines;
    private final ClaimRepaymentRepository repayments;
    private final com.aditya.personalbudget.repository.AttachmentRepository attachments;
    private final AttachmentService attachmentService;
    private final com.aditya.personalbudget.repository.ClaimInterestPostingRepository interestPostings;
    private final CategoryRepository categories;
    private final ChitRepository chits;
    private final HostedChitRepository hostedChits;

    public LedgerService(AccountRepository accounts, JournalEntryRepository entries, JournalLineRepository lines,
                         ClaimRepaymentRepository repayments, CategoryRepository categories, ChitRepository chits,
                         com.aditya.personalbudget.repository.ClaimInterestPostingRepository interestPostings,
                         com.aditya.personalbudget.repository.AttachmentRepository attachments, AttachmentService attachmentService,
                         HostedChitRepository hostedChits) {
        this.hostedChits = hostedChits;
        this.attachments = attachments;
        this.attachmentService = attachmentService;
        this.interestPostings = interestPostings;
        this.accounts = accounts;
        this.entries = entries;
        this.lines = lines;
        this.repayments = repayments;
        this.categories = categories;
        this.chits = chits;
    }

    /** A well-known system account (see {@link DefaultChartOfAccounts}). */
    public Account systemAccount(String code) {
        return accounts.findByTenantIdAndCode(UserContext.tenantId(), code)
                .orElseThrow(() -> new BusinessException("System account " + code + " is missing"));
    }

    /**
     * Only manual journal vouchers are edited in the journal. Everything posted automatically by a
     * feature (an expense, a transfer, a chit payment, money lent ...) is locked there and is
     * changed through that feature, or corrected with a reversal.
     */
    public static boolean isManual(JournalEntry entry) {
        return entry.getSourceType() == null;
    }

    /** Expenses posted from the Expenses screen (QUICK + EXPENSE covers entries made before the split). */
    public static boolean isExpense(JournalEntry entry) {
        return SOURCE_EXPENSE.equals(entry.getSourceType())
                || (SOURCE_QUICK.equals(entry.getSourceType()) && entry.getVoucherType() == VoucherType.EXPENSE);
    }

    // ================================================================== posting

    @Transactional
    public JournalEntry post(JournalDraft draft) {
        Long tenantId = UserContext.tenantId();
        List<JournalDraft.Line> resolved = resolve(tenantId, draft);
        BigDecimal total = total(resolved);

        JournalEntry entry = new JournalEntry();
        entry.setTenantId(tenantId);
        entry.setEntryNo(nextEntryNo(tenantId, draft.voucherType()));
        fillHeader(entry, draft, total);
        entry.setCreatedBy(UserContext.username());
        entry.setCreatedAt(LocalDateTime.now());
        entry = entries.save(entry);

        saveLines(tenantId, entry.getId(), resolved);
        return entry;
    }

    /** Replaces the content of an existing entry, keeping its number. */
    @Transactional
    public JournalEntry repost(Long entryId, JournalDraft draft) {
        return repost(entryId, draft, null);
    }

    /**
     * Replaces the content of an existing entry; with {@code expectedVersion} the edit is refused when
     * someone else changed the entry since the editor loaded it.
     */
    @Transactional
    public JournalEntry repost(Long entryId, JournalDraft draft, Long expectedVersion) {
        Long tenantId = UserContext.tenantId();
        JournalEntry entry = entries.findByIdAndTenantId(entryId, tenantId)
                .orElseThrow(() -> new NotFoundException("Journal entry", entryId));
        List<JournalDraft.Line> resolved = resolve(tenantId, draft);
        BigDecimal total = total(resolved);

        lines.deleteAll(lines.findByJournalEntryId(entryId));
        fillHeader(entry, draft, total);
        entry.setVersion(expectedVersion);
        entry = entries.save(entry);
        saveLines(tenantId, entryId, resolved);
        return entry;
    }

    @Transactional
    public void delete(Long entryId) {
        JournalEntry entry = entries.findByIdAndTenantId(entryId, UserContext.tenantId())
                .orElseThrow(() -> new NotFoundException("Journal entry", entryId));
        lines.deleteAll(lines.findByJournalEntryId(entry.getId()));
        attachmentService.deleteForEntry(entry.getId());   // its evidence goes with it
        entries.deleteById(entry.getId());
    }

    // ================================================================== queries

    public JournalEntry get(Long entryId) {
        return entries.findByIdAndTenantId(entryId, UserContext.tenantId())
                .orElseThrow(() -> new NotFoundException("Journal entry", entryId));
    }

    public LedgerSnapshot snapshot() {
        Long tenantId = UserContext.tenantId();
        return new LedgerSnapshot(accounts.findByTenantId(tenantId), entries.findByTenantId(tenantId),
                lines.findByTenantId(tenantId), categories.findByTenantId(tenantId), chits.findByTenantId(tenantId));
    }

    /** Converts entries to views with their lines and account names (one pass, no N+1 lookups). */
    public List<EntryView> toViews(Collection<JournalEntry> list) {
        if (list.isEmpty()) {
            return List.of();
        }
        Map<Long, Account> accountById = accounts.findByTenantId(UserContext.tenantId()).stream()
                .collect(Collectors.toMap(Account::getId, Function.identity()));
        Map<Long, String> categoryName = categories.findByTenantId(UserContext.tenantId()).stream()
                .collect(Collectors.toMap(Category::getId, Category::getName));
        Map<Long, String> chitName = chits.findByTenantId(UserContext.tenantId()).stream()
                .collect(Collectors.toMap(Chit::getId, Chit::getName));
        Set<Long> ids = list.stream().map(JournalEntry::getId).collect(Collectors.toSet());
        Map<Long, List<JournalLine>> linesByEntry = lines.findByJournalEntryIdIn(ids).stream()
                .collect(Collectors.groupingBy(JournalLine::getJournalEntryId));
        // reversal entries keyed by the entry they reverse, and every entry number (for "reversal of")
        List<JournalEntry> all = entries.findByTenantId(UserContext.tenantId());
        Map<Long, JournalEntry> reversals = all.stream()
                .filter(x -> SOURCE_REVERSAL.equals(x.getSourceType()) && x.getSourceId() != null)
                .collect(Collectors.toMap(JournalEntry::getSourceId, Function.identity(), (a, b) -> a));
        Map<Long, String> numbers = all.stream().collect(Collectors.toMap(JournalEntry::getId, JournalEntry::getEntryNo));
        Map<Long, Integer> evidence = attachments.countsByEntry(UserContext.tenantId());

        return list.stream().map(e -> {
            List<LineView> lineViews = linesByEntry.getOrDefault(e.getId(), List.of()).stream()
                    .sorted((a, b) -> a.getLineNo().compareTo(b.getLineNo()))
                    .map(l -> {
                        Account a = accountById.get(l.getAccountId());
                        String shown = l.getCategoryId() != null ? categoryName.getOrDefault(l.getCategoryId(), a.getName())
                                : l.getChitId() != null ? chitName.getOrDefault(l.getChitId(), a.getName()) : a.getName();
                        return new LineView(l.getId(), l.getLineNo(), l.getAccountId(), a.getCode(), shown,
                                a.getAccountClass(), l.getDebit(), l.getCredit(), l.getMemo(),
                                l.getCategoryId(), l.getChitId(), a.getName(), l.getHostedChitId());
                    })
                    .toList();
            Lock lock = lockOf(e, reversals, numbers);
            return new EntryView(e.getId(), e.getEntryNo(), e.getEntryDate(), e.getVoucherType(),
                    voucherLabel(e), e.getNarration(), e.getReference(), e.getParty(), e.getAmount(),
                    e.getSourceType(), e.getSourceId(), isManual(e), e.getCreatedBy(), e.getCreatedAt(), lineViews,
                    lock.reason(), lock.manageAt(), lock.reversible(), lock.reversedBy(), lock.reversalOf(),
                    claimIdOf(e), e.getVersion(), evidence.getOrDefault(e.getId(), 0));
        }).toList();
    }

    // ================================================================== locking

    /** Why an entry cannot be edited in the journal, and where it is managed instead. */
    private record Lock(String reason, String manageAt, boolean reversible, String reversedBy, String reversalOf) {
    }

    private static Lock lockOf(JournalEntry e, Map<Long, JournalEntry> reversals, Map<Long, String> numbers) {
        JournalEntry reversal = reversals.get(e.getId());
        String reversedBy = reversal == null ? null : reversal.getEntryNo();
        String source = e.getSourceType();
        if (source == null) {
            return new Lock(null, null, false, reversedBy, null);
        }
        if (isExpense(e)) {
            return new Lock("Posted from Expenses. Edit or delete it there.", "expenses", false, reversedBy, null);
        }
        return switch (source) {
            case SOURCE_ACCOUNT_OPENING ->
                    new Lock("Opening balance. Change it on the account.", "accounts", false, reversedBy, null);
            case SOURCE_CHIT_INSTALLMENT, SOURCE_CHIT_PAYOUT ->
                    new Lock("Chit posting. Undo it from the Chits screen.", "chits", false, reversedBy, null);
            case HostedChitService.SOURCE_COLLECTION, HostedChitService.SOURCE_PAYOUT, HostedChitService.SOURCE_COMMISSION ->
                    new Lock("Posted from a chit you host. Edit or undo it on Host a Chit.", "host-chits", false, reversedBy, null);
            case HostedChitBookService.SOURCE_TRANSFER ->
                    new Lock("A chit transfer. Edit or undo it on Host a Chit, Chit accounts.", "host-chits/accounts", false, reversedBy, null);
            case SOURCE_CLAIM, SOURCE_CLAIM_REPAYMENT, SOURCE_CLAIM_INTEREST ->
                    new Lock("Money lent, borrowed or its interest. Manage it from Expenses.", "expenses", false, reversedBy, null);
            case SOURCE_REFUND ->
                    new Lock("Refund of " + numbers.getOrDefault(e.getSourceId(), "an expense") + ". Undo it from Expenses.",
                            "expenses", false, null, null);
            case SOURCE_REVERSAL ->
                    new Lock("Reversal entry. It cannot be changed.", null, false, null, numbers.get(e.getSourceId()));
            default -> new Lock(reversedBy == null
                    ? "Posted automatically. Reverse it to correct the books."
                    : "Reversed by " + reversedBy + ".", null, reversedBy == null, reversedBy, null);
        };
    }

    /** The voucher's name; a repayment says whether it was partial or final, as its narration does. */
    private static String voucherLabel(JournalEntry e) {
        String label = e.getVoucherType().getLabel();
        if (SOURCE_CLAIM_REPAYMENT.equals(e.getSourceType()) && e.getNarration() != null
                && (e.getVoucherType() == VoucherType.REPAYMENT || e.getVoucherType() == VoucherType.REPAYMENT_MADE)) {
            if (e.getNarration().startsWith("Partial ")) {
                return "Partial " + label;
            }
            if (e.getNarration().startsWith("Final ")) {
                return "Final " + label;
            }
        }
        return label;
    }

    /** The claim an entry belongs to: the original payment, a repayment or a write-off. */
    private Long claimIdOf(JournalEntry e) {
        if (SOURCE_CLAIM.equals(e.getSourceType())) {
            return e.getSourceId();
        }
        if (SOURCE_CLAIM_INTEREST.equals(e.getSourceType())) {
            return interestPostings.findById(e.getSourceId()).map(p -> p.getClaimId()).orElse(null);
        }
        if (SOURCE_CLAIM_REPAYMENT.equals(e.getSourceType())) {
            return repayments.findById(e.getSourceId()).map(ClaimRepayment::getClaimId).orElse(null);
        }
        return null;
    }

    /** Posts the mirror image of an automatic entry (debits become credits) and links it to the original. */
    @Transactional
    public JournalEntry reverse(Long entryId, LocalDate date) {
        JournalEntry original = get(entryId);
        EntryView view = toViews(List.of(original)).getFirst();
        if (!view.reversible()) {
            throw new BusinessException(view.reversedBy() != null
                    ? original.getEntryNo() + " is already reversed by " + view.reversedBy()
                    : view.lockReason() != null ? view.lockReason() : "Manual journals are edited directly");
        }
        JournalDraft draft = JournalDraft.of(date != null ? date : LocalDate.now(), VoucherType.REVERSAL,
                        "Reversal of " + original.getEntryNo() + ": " + original.getNarration())
                .party(original.getParty())
                .reference(original.getReference())
                .source(SOURCE_REVERSAL, original.getId());
        for (JournalLine l : lines.findByJournalEntryId(original.getId())) {
            draft.line(new JournalDraft.Line(l.getAccountId(), l.getCategoryId(), l.getChitId(), l.getCredit(), l.getDebit(), l.getMemo(),
                    l.getHostedChitId()));
        }
        return post(draft);
    }

    // ================================================================== helpers

    /**
     * Checks the draft and returns its lines with categories filled in: an Expenses / Income line without
     * one gets Miscellaneous / Other income.
     */
    private List<JournalDraft.Line> resolve(Long tenantId, JournalDraft draft) {
        if (draft.date() == null) {
            throw new BusinessException("Entry date is required");
        }
        if (draft.lines().size() < 2) {
            throw new BusinessException("A journal needs at least one debit and one credit line");
        }
        BigDecimal debit = Money.ZERO;
        BigDecimal credit = Money.ZERO;
        Set<String> distinct = new HashSet<>();
        List<JournalDraft.Line> resolved = new ArrayList<>();
        for (JournalDraft.Line line : draft.lines()) {
            boolean isDebit = Money.isPositive(line.debit());
            boolean isCredit = Money.isPositive(line.credit());
            if (isDebit == isCredit) {
                throw new BusinessException("Each line must have either a debit or a credit amount");
            }
            Account account = accounts.findByIdAndTenantId(line.accountId(), tenantId)
                    .orElseThrow(() -> new NotFoundException("Account", line.accountId()));
            if (!Boolean.TRUE.equals(account.getActive())) {
                throw new BusinessException("Account '" + account.getName() + "' is inactive");
            }
            Long categoryId = null;
            Long chitId = null;
            CategoryKind kind = CategoryKind.of(account.getAccountClass());
            if (kind != null) {
                Category category = line.categoryId() != null
                        ? categories.findByIdAndTenantId(line.categoryId(), tenantId)
                            .orElseThrow(() -> new NotFoundException("Category", line.categoryId()))
                        : categories.findBySystemKey(tenantId, kind == CategoryKind.EXPENSE
                            ? DefaultChartOfAccounts.MISC_EXPENSE : DefaultChartOfAccounts.OTHER_INCOME)
                            .orElseThrow(() -> new BusinessException("Pick a category for the " + account.getName() + " line"));
                if (category.getKind() != kind) {
                    throw new BusinessException("'" + category.getName() + "' is not an " + kind.getLabel().toLowerCase()
                            + " category, so it cannot go on the " + account.getName() + " line");
                }
                if (LedgerSnapshot.budgetOnly(category)) {
                    throw new BusinessException("'" + category.getName() + "' fills itself from the installments paid on the "
                            + "Chits page; record chit payments there");
                }
                categoryId = category.getId();
            }
            if (account.getAccountType() == AccountType.CHIT_FUND) {
                if (line.chitId() == null) {
                    throw new BusinessException("Lines on " + account.getName() + " need the chit they belong to");
                }
                chitId = chits.findByIdAndTenantId(line.chitId(), tenantId)
                        .orElseThrow(() -> new NotFoundException("Chit", line.chitId())).getId();
            }
            if (line.hostedChitId() != null && hostedChits.findByIdAndTenantId(line.hostedChitId(), tenantId).isEmpty()) {
                throw new NotFoundException("Hosted chit", line.hostedChitId());
            }
            distinct.add(account.getId() + "/" + categoryId + "/" + chitId);
            debit = debit.add(Money.nz(line.debit()));
            credit = credit.add(Money.nz(line.credit()));
            resolved.add(new JournalDraft.Line(account.getId(), categoryId, chitId, line.debit(), line.credit(), line.memo(),
                    line.hostedChitId()));
        }
        if (distinct.size() < 2) {
            throw new BusinessException("Debit and credit must use different accounts");
        }
        if (debit.compareTo(credit) != 0) {
            throw new BusinessException("Journal is not balanced: debits " + debit.toPlainString()
                    + " vs credits " + credit.toPlainString());
        }
        return resolved;
    }

    private static BigDecimal total(List<JournalDraft.Line> lines) {
        return Money.round(lines.stream().map(l -> Money.nz(l.debit())).reduce(Money.ZERO, BigDecimal::add));
    }

    private void fillHeader(JournalEntry entry, JournalDraft draft, BigDecimal total) {
        entry.setEntryDate(draft.date());
        entry.setVoucherType(draft.voucherType());
        String narration = draft.narration();
        entry.setNarration(narration == null || narration.isBlank() ? draft.voucherType().getLabel() : narration);
        entry.setReference(draft.reference());
        entry.setParty(draft.party());
        entry.setAmount(total);
        entry.setSourceType(draft.sourceType());
        entry.setSourceId(draft.sourceId());
    }

    private void saveLines(Long tenantId, Long entryId, List<JournalDraft.Line> draftLines) {
        List<JournalLine> rows = new ArrayList<>();
        int lineNo = 1;
        for (JournalDraft.Line l : draftLines) {
            JournalLine row = new JournalLine();
            row.setTenantId(tenantId);
            row.setJournalEntryId(entryId);
            row.setLineNo(lineNo++);
            row.setAccountId(l.accountId());
            row.setCategoryId(l.categoryId());
            row.setChitId(l.chitId());
            row.setHostedChitId(l.hostedChitId());
            row.setDebit(Money.round(l.debit()));
            row.setCredit(Money.round(l.credit()));
            row.setMemo(l.memo());
            rows.add(row);
        }
        lines.saveAll(rows);
    }

    /** Next number per voucher prefix, e.g. EX-000043. */
    private String nextEntryNo(Long tenantId, VoucherType type) {
        String prefix = type.getPrefix() + "-";
        int max = entries.findByTenantId(tenantId).stream()
                .map(JournalEntry::getEntryNo)
                .filter(no -> no.startsWith(prefix))
                .mapToInt(no -> parseIntSafe(no.substring(prefix.length())))
                .max().orElse(0);
        return prefix + String.format("%06d", max + 1);
    }

    private static int parseIntSafe(String text) {
        try {
            return Integer.parseInt(text);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    /** Ids of every entry that has a line on the given account. */
    public Set<Long> entryIdsTouchingAccount(Long accountId) {
        return lines.findByAccountId(accountId).stream().map(JournalLine::getJournalEntryId).collect(Collectors.toSet());
    }

    /** Ids of every entry with a line in the given category. */
    public Set<Long> entryIdsInCategory(Long categoryId) {
        return lines.findByTenantId(UserContext.tenantId()).stream().filter(l -> categoryId.equals(l.getCategoryId()))
                .map(JournalLine::getJournalEntryId).collect(Collectors.toSet());
    }

    public List<JournalEntry> entriesBetween(LocalDate from, LocalDate to) {
        return entries.findByTenantIdAndEntryDateBetween(UserContext.tenantId(), from, to);
    }
}
